// Code generated by entc, DO NOT EDIT.

package mainingre

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/faomg201/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// MAININGREDIENTNAME applies equality check predicate on the "MAIN_INGREDIENT_NAME" field. It's identical to MAININGREDIENTNAMEEQ.
func MAININGREDIENTNAME(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMEEQ applies the EQ predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEEQ(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMENEQ applies the NEQ predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMENEQ(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMEIn applies the In predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEIn(vs ...string) predicate.Mainingre {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Mainingre(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMAININGREDIENTNAME), v...))
	})
}

// MAININGREDIENTNAMENotIn applies the NotIn predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMENotIn(vs ...string) predicate.Mainingre {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Mainingre(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMAININGREDIENTNAME), v...))
	})
}

// MAININGREDIENTNAMEGT applies the GT predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEGT(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMEGTE applies the GTE predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEGTE(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMELT applies the LT predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMELT(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMELTE applies the LTE predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMELTE(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMEContains applies the Contains predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEContains(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMEHasPrefix applies the HasPrefix predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEHasPrefix(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMEHasSuffix applies the HasSuffix predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEHasSuffix(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMEEqualFold applies the EqualFold predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEEqualFold(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// MAININGREDIENTNAMEContainsFold applies the ContainsFold predicate on the "MAIN_INGREDIENT_NAME" field.
func MAININGREDIENTNAMEContainsFold(v string) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldMAININGREDIENTNAME), v))
	})
}

// HasMAININGRERECORD applies the HasEdge predicate on the "MAININGRE_RECORD" edge.
func HasMAININGRERECORD() predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MAININGRERECORDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MAININGRERECORDTable, MAININGRERECORDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMAININGRERECORDWith applies the HasEdge predicate on the "MAININGRE_RECORD" edge with a given conditions (other predicates).
func HasMAININGRERECORDWith(preds ...predicate.Recordfood) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(MAININGRERECORDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MAININGRERECORDTable, MAININGRERECORDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Mainingre) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Mainingre) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Mainingre) predicate.Mainingre {
	return predicate.Mainingre(func(s *sql.Selector) {
		p(s.Not())
	})
}
