// Code generated by entc, DO NOT EDIT.

package foodmenu

import (
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/faomg201/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// FOODMENUNAME applies equality check predicate on the "FOODMENU_NAME" field. It's identical to FOODMENUNAMEEQ.
func FOODMENUNAME(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMEEQ applies the EQ predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEEQ(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMENEQ applies the NEQ predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMENEQ(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMEIn applies the In predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEIn(vs ...string) predicate.FOODMENU {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FOODMENU(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFOODMENUNAME), v...))
	})
}

// FOODMENUNAMENotIn applies the NotIn predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMENotIn(vs ...string) predicate.FOODMENU {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FOODMENU(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFOODMENUNAME), v...))
	})
}

// FOODMENUNAMEGT applies the GT predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEGT(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMEGTE applies the GTE predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEGTE(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMELT applies the LT predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMELT(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMELTE applies the LTE predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMELTE(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMEContains applies the Contains predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEContains(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMEHasPrefix applies the HasPrefix predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEHasPrefix(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMEHasSuffix applies the HasSuffix predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEHasSuffix(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMEEqualFold applies the EqualFold predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEEqualFold(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFOODMENUNAME), v))
	})
}

// FOODMENUNAMEContainsFold applies the ContainsFold predicate on the "FOODMENU_NAME" field.
func FOODMENUNAMEContainsFold(v string) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFOODMENUNAME), v))
	})
}

// HasFOODMENURECORD applies the HasEdge predicate on the "FOODMENU_RECORD" edge.
func HasFOODMENURECORD() predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FOODMENURECORDTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FOODMENURECORDTable, FOODMENURECORDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFOODMENURECORDWith applies the HasEdge predicate on the "FOODMENU_RECORD" edge with a given conditions (other predicates).
func HasFOODMENURECORDWith(preds ...predicate.Recordfood) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FOODMENURECORDInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FOODMENURECORDTable, FOODMENURECORDColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.FOODMENU) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.FOODMENU) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FOODMENU) predicate.FOODMENU {
	return predicate.FOODMENU(func(s *sql.Selector) {
		p(s.Not())
	})
}
