/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersRecordfood
 */
export interface ControllersRecordfood {
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordfood
     */
    recordFOODMENU?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordfood
     */
    recordINGREDIENT?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordfood
     */
    recordSOURCE?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersRecordfood
     */
    recordUSER?: number;
}

export function ControllersRecordfoodFromJSON(json: any): ControllersRecordfood {
    return ControllersRecordfoodFromJSONTyped(json, false);
}

export function ControllersRecordfoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersRecordfood {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordFOODMENU': !exists(json, 'recordFOODMENU') ? undefined : json['recordFOODMENU'],
        'recordINGREDIENT': !exists(json, 'recordINGREDIENT') ? undefined : json['recordINGREDIENT'],
        'recordSOURCE': !exists(json, 'recordSOURCE') ? undefined : json['recordSOURCE'],
        'recordUSER': !exists(json, 'recordUSER') ? undefined : json['recordUSER'],
    };
}

export function ControllersRecordfoodToJSON(value?: ControllersRecordfood | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recordFOODMENU': value.recordFOODMENU,
        'recordINGREDIENT': value.recordINGREDIENT,
        'recordSOURCE': value.recordSOURCE,
        'recordUSER': value.recordUSER,
    };
}


