/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFOODMENUEdges,
    EntFOODMENUEdgesFromJSON,
    EntFOODMENUEdgesFromJSONTyped,
    EntFOODMENUEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFOODMENU
 */
export interface EntFOODMENU {
    /**
     * FOODMENUNAME holds the value of the "FOODMENU_NAME" field.
     * @type {string}
     * @memberof EntFOODMENU
     */
    fOODMENUNAME?: string;
    /**
     * 
     * @type {EntFOODMENUEdges}
     * @memberof EntFOODMENU
     */
    edges?: EntFOODMENUEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntFOODMENU
     */
    id?: number;
}

export function EntFOODMENUFromJSON(json: any): EntFOODMENU {
    return EntFOODMENUFromJSONTyped(json, false);
}

export function EntFOODMENUFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFOODMENU {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fOODMENUNAME': !exists(json, 'FOODMENU_NAME') ? undefined : json['FOODMENU_NAME'],
        'edges': !exists(json, 'edges') ? undefined : EntFOODMENUEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntFOODMENUToJSON(value?: EntFOODMENU | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'FOODMENU_NAME': value.fOODMENUNAME,
        'edges': EntFOODMENUEdgesToJSON(value.edges),
        'id': value.id,
    };
}


