/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRecordfoodEdges,
    EntRecordfoodEdgesFromJSON,
    EntRecordfoodEdgesFromJSONTyped,
    EntRecordfoodEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRecordfood
 */
export interface EntRecordfood {
    /**
     * 
     * @type {EntRecordfoodEdges}
     * @memberof EntRecordfood
     */
    edges?: EntRecordfoodEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRecordfood
     */
    id?: number;
}

export function EntRecordfoodFromJSON(json: any): EntRecordfood {
    return EntRecordfoodFromJSONTyped(json, false);
}

export function EntRecordfoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRecordfood {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntRecordfoodEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRecordfoodToJSON(value?: EntRecordfood | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntRecordfoodEdgesToJSON(value.edges),
        'id': value.id,
    };
}


