/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRecordfood,
    EntRecordfoodFromJSON,
    EntRecordfoodFromJSONTyped,
    EntRecordfoodToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSourceEdges
 */
export interface EntSourceEdges {
    /**
     * SOURCERECORD holds the value of the SOURCE_RECORD edge.
     * @type {Array<EntRecordfood>}
     * @memberof EntSourceEdges
     */
    sourcerecord?: Array<EntRecordfood>;
}

export function EntSourceEdgesFromJSON(json: any): EntSourceEdges {
    return EntSourceEdgesFromJSONTyped(json, false);
}

export function EntSourceEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSourceEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sourcerecord': !exists(json, 'sourcerecord') ? undefined : ((json['sourcerecord'] as Array<any>).map(EntRecordfoodFromJSON)),
    };
}

export function EntSourceEdgesToJSON(value?: EntSourceEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sourcerecord': value.sourcerecord === undefined ? undefined : ((value.sourcerecord as Array<any>).map(EntRecordfoodToJSON)),
    };
}


