/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRecordfood,
    EntRecordfoodFromJSON,
    EntRecordfoodFromJSONTyped,
    EntRecordfoodToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * USERRECORD holds the value of the USER_RECORD edge.
     * @type {Array<EntRecordfood>}
     * @memberof EntUserEdges
     */
    userrecord?: Array<EntRecordfood>;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userrecord': !exists(json, 'userrecord') ? undefined : ((json['userrecord'] as Array<any>).map(EntRecordfoodFromJSON)),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userrecord': value.userrecord === undefined ? undefined : ((value.userrecord as Array<any>).map(EntRecordfoodToJSON)),
    };
}


