// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// FOODMENU is the predicate function for foodmenu builders.
type FOODMENU func(*sql.Selector)

// Mainingre is the predicate function for mainingre builders.
type Mainingre func(*sql.Selector)

// Recordfood is the predicate function for recordfood builders.
type Recordfood func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
